FROM node:20-alpine as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
